version: "3.7"

services:
  nodered:
    image: nodered/node-red:latest
    ports: 
      - "6008:1880"
    networks:
      - workshop-net1
    volumes: 
      - workshop-nodered:/data

  database:
    image: bitnami/mongodb:latest
    networks:
      - workshop-net1
    volumes: 
      - workshop-db:/bitnami/mongodb
    environment:
      - MONGODB_DISABLE_SYSTEM_LOG=false
      - MONGODB_SYSTEM_LOG_VERBOSITY=0
      - MONGODB_ENABLE_DIRECTORY_PER_DB=true
      - MONGODB_ROOT_PASSWORD=password123
      #create a database:
      - MONGODB_DATABASE=database123
      - MONGODB_USERNAME=user123
      - MONGODB_PASSWORD=password123
    
  mosquitto:
    image: eclipse-mosquitto:latest
    ports: 
      - "6004:1883"
    networks:
      - workshop-net1
    volumes:
      - workshop-mosquitto:/mosquitto/log
    configs: 
      - source: mosquitto-config
        target: /mosquitto/config/mosquitto.conf
    secrets: 
      - source: mosquitto-password
        target: /mosquitto/passwd
  
  mongo-express: 
    image: mongo-express:latest
    ports:
      - "8058:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: "database"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "workshop"
      
    networks: 
      - workshop-net1
    



networks:
  workshop-net1:
    external: true


volumes: 
  workshop-db:
    external: true
  workshop-nodered:
    external: true
  workshop-mosquitto:
    external: true
    

configs:
  mosquitto-config:
    external: true
    
secrets:
  mosquitto-password:
    external: true


    
